export const ROLES = {
  ADMIN: 'ADMIN',
  SHOPKEEPER: 'SHOPKEEPER',
  ACCOUNTANT: 'ACCOUNTANT',
  MANAGER: 'MANAGER',
} as const;

export type RoleName = keyof typeof ROLES;

export const ROLE_IDS = {
  ADMIN: 1,
  SHOPKEEPER: 2,
  ACCOUNTANT: 3,
  MANAGER: 4,
} as const;

export const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;

export const SALE_STATUS = {
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
  CANCELLED: 'CANCELLED',
} as const;

export const PAYMENT_STATUS = {
  ROUGH: 'ROUGH',
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
} as const;

export const INVOICE_STATUS = {
  FINALIZED: 'FINALIZED',
  CANCELLED: 'CANCELLED',
} as const;

export const MOVEMENT_TYPES = {
  OPENING_STOCK: 'OPENING_STOCK',
  PURCHASE_IN: 'PURCHASE_IN',
  SALE_OUT: 'SALE_OUT',
  SALE_CANCEL_REVERSAL_IN: 'SALE_CANCEL_REVERSAL_IN',
  SALE_RETURN_IN: 'SALE_RETURN_IN',
  ADJUSTMENT_IN: 'ADJUSTMENT_IN',
  ADJUSTMENT_OUT: 'ADJUSTMENT_OUT',
  DAMAGE_OUT: 'DAMAGE_OUT',
} as const;

export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  IDEMPOTENCY_MISMATCH: 'IDEMPOTENCY_MISMATCH',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;
